apiVersion: v1
kind: Secret
metadata:
  name: mysecret
  annotations:
    avp.kubernetes.io/path: "kv-v2/data/argocd"
type: Opaque
stringData:
  TOKEN: <password>
---
apiVersion: v1
kind: Secret
metadata:
  name: vault-secret
  annotations:
    avp.kubernetes.io/path: "creds/data/app"
type: Opaque
stringData:
  username: <username>
  password: <password>
  apikey: <apikey>